version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
  test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      - run: chmod +x ./kubectl
      - run: ./kubectl --kubeconfig=./config get pods

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
